# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [52]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [53]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.13459947 0.76469283 0.66942853 ... 0.7655767  0.31073572 0.56088774]
 [0.59580571 0.89281666 0.0595464  ... 0.71434389 0.40760072 0.53621183]
 [0.88603215 0.63689147 0.66192492 ... 0.39885473 0.03490612 0.04501626]
 ...
 [0.01214655 0.41173136 0.37523404 ... 0.34253074 0.30616026 0.52840598]
 [0.43246295 0.2504309  0.13702488 ... 0.44768959 0.44325229 0.96649677]
 [0.26999016 0.8780808  0.68674036 ... 0.86371381 0.64512144 0.09170983]]
[[0.53971579 0.75217941 0.29723003 ... 0.78014092 0.55562596 0.38060743]
 [0.19050633 0.84998003 0.1095887  ... 0.02689427 0.02948785 0.91744073]
 [0.54957731 0.31793174 0.73379483 ... 0.75897667 0.17829864 0.10605219]
 ...
 [0.53976395 0.57979761 0.80659075 ... 0.8938869  0.58615386 0.10601003]
 [0.53693403 0.34881952 0.18640953 ... 0.26905905 0.70173895 0.03640388]
 [0.17006259 0.44131803 0.82278501 ... 0.92886855 0.26959994 0.86421528]]


Без использования numpy

In [54]:
def mult(a, b):
    result = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]

    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [55]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [56]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 1.43 s, sys: 0 ns, total: 1.43 s
Wall time: 1.47 s


In [57]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 4.37 ms, sys: 0 ns, total: 4.37 ms
Wall time: 7.56 ms


In [58]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5351275806096965e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [59]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.72252783 0.61648852 0.895936  ] [0.00525765 0.97712213 0.8661075 ]


In [60]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [61]:
def np_scalar_product(a,b):
    s = 0
    s = np.dot(a, b)
    return s

In [62]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 22 µs, sys: 0 ns, total: 22 µs
Wall time: 25.7 µs
CPU times: user 41 µs, sys: 5 µs, total: 46 µs
Wall time: 50.5 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** numpy более эффективен благодаря векторизированным операциям, написанному на C и оптимизированным алгоритмам. В результате, вычисления в NumPy обычно выполняются значительно быстрее.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [63]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = None
  diagonal_elements = np.diag(a)
  even_diagonal_elements = diagonal_elements[diagonal_elements % 2 == 0]
  if even_diagonal_elements.size == 0:
    res = 0
  else:
    res = np.sum(even_diagonal_elements)

  return res

In [64]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[5, 6, 2, 7, 3],
       [6, 1, 8, 3, 5],
       [2, 5, 3, 8, 8],
       [3, 3, 1, 1, 2],
       [3, 4, 1, 1, 7]])

In [65]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 89 µs, sys: 11 µs, total: 100 µs
Wall time: 105 µs


0

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [66]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    X = np.array(A)
    cumsums = np.cumsum(X, axis=1)
    result = cumsums / np.arange(1, X.shape[1] + 1)
    return result

In [67]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.1395899  0.62486623 0.47100012 0.48509905 0.87214281 0.27284514
 0.45844611 0.98293621 0.37619488 0.50618298 0.13557494 0.73760153
 0.70042036 0.48513781 0.9760426  0.32762028 0.15972094 0.84926198
 0.69022129 0.21087901 0.325803   0.1692558  0.59885052 0.65911879
 0.74836724 0.60384463 0.25373147 0.69678273 0.91780024 0.5562659
 0.75898991 0.33649107 0.00602085 0.17819047 0.0893673  0.17192444
 0.25185295 0.92089971 0.58811199 0.52673582 0.37533737 0.1630583
 0.4208406  0.03456446 0.76384666 0.12665168 0.55029362 0.87051633
 0.31783311 0.47256882 0.77717427 0.12404491 0.9537158  0.76802752
 0.81593128 0.16415027 0.0686712  0.05547919 0.89988265 0.5835152
 0.63316478 0.2629734  0.36200035 0.06079633 0.81852326 0.16033849
 0.83397025 0.15779249 0.78083313 0.10619164 0.77577971 0.08753802
 0.92894755 0.50946498 0.83140713 0.27233225 0.48599086 0.30236976
 0.43996652 0.41774554 0.39450679 0.54291246 0.54105448 0.73985545
 0.18421349 0.78731453 0.36534035 0.31174524 0.36898366 0.3497496

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [68]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    result = None
    encoded_array = []
    count_array = []
    current_count = 1
    for i in range(1, len(a)):
        if a[i] == a[i-1]:
            current_count += 1
        else:
            encoded_array.append(a[i-1])
            count_array.append(current_count)
            current_count = 1
    encoded_array.append(a[-1])
    count_array.append(current_count)
    result = (np.array(encoded_array), np.array(count_array))

    return result

In [69]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 37 µs, sys: 4 µs, total: 41 µs
Wall time: 46 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [70]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    result = None
    X_modified = X.copy()
    X_modified[1::2] = a
    X_modified[::2] = X_modified[::2] ** 3
    X_modified_reversed = X_modified[::-1]
    result = np.concatenate((X, X_modified_reversed))
    return result

In [71]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 1.07 ms, sys: 2 µs, total: 1.07 ms
Wall time: 2.46 ms
